# Generated by Django 4.1.7 on 2023-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeBg info')),
                ('text', models.TextField(verbose_name='HomeBg text')),
                ('button_name', models.CharField(max_length=60, verbose_name='HomeBg button name')),
            ],
        ),
    ]
