# Generated by Django 4.1.7 on 2023-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='link1_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Slider link1 name'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='link2_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Slider link2 name'),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='link3_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Slider link3 name'),
        ),
    ]
