# Generated by Django 4.1.7 on 2023-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lastest_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastest_episode',
            name='file',
            field=models.FileField(blank=True, upload_to='file', verbose_name='file'),
        ),
    ]
