# Generated by Django 4.1.7 on 2023-03-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lastest_episode_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Topic name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Topic image')),
                ('count', models.PositiveIntegerField(verbose_name='Episode count')),
            ],
        ),
    ]
