# Generated by Django 4.1.7 on 2023-03-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Trending text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Trending images')),
                ('button1', models.PositiveBigIntegerField(default=0, verbose_name='Button1')),
                ('button2', models.PositiveBigIntegerField(default=0, verbose_name='Button2')),
                ('button3', models.PositiveBigIntegerField(default=0, verbose_name='Button3')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after', to='main.homeslider')),
            ],
        ),
    ]
