# Generated by Django 4.1.7 on 2023-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_boody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='About boody name')),
                ('text', models.TextField(verbose_name='About boody text')),
                ('img', models.ImageField(upload_to='images', verbose_name='About boody image')),
            ],
        ),
    ]
