# Generated by Django 4.1.7 on 2023-03-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_aboutslider_img_aboutslider_imges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutslider',
            name='imges',
        ),
    ]
