# Generated by Django 4.1.7 on 2023-03-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_aboutslider_imges'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutslider',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Slider image'),
        ),
    ]
