# Generated by Django 4.1.7 on 2023-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutslider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutslider',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Slider image'),
        ),
    ]
